### ISSUE TITLE
插件作者您好！咨询两个小问题，关于词库的定型文和编辑权限

### ISSUE THREAD

**Issue by DeepseaXX** [BSTluo/koishi-plugin-word-core#10]
阅读了readme的关于鱼的事例还是有一些不懂，请问我能否实现以下玩法？

词库“饭”中内容有“米饭”“饺子”“面条”
词库“水”中有内容“开水”“冰水”
发送问题“今天吃什么”
自动回复“你就吃[饭]，喝[水]吧”
[饭]将随机从词库“饭”中抽取一项，[水]从词库“水”中随机抽取，完成定型文。

以及，词库想由所有用户来完成，所以期待可以加入一个选项，设置该词库的编辑权限默认赋予给所有人……

期待您的回答！

**Comment by BSTluo** [comment]
（稍等！我干个饭之后回复你！）

**Comment by BSTluo** [comment]
okk！我回来了！非常感谢你使用word-core！

首先！word-core词库插件是通过设置问答来让机器人检测到某些触发的时候回复！而设置问答的时候！允许一个触发词包含多个回答！

![image](https://github.com/user-attachments/assets/6e731d22-f05d-4eea-a036-b9e56755f2c8)

**Comment by BSTluo** [comment]
你看到的钓鱼的示例！
```
(+:物品名称:数量)
为触发者增加某个物品
```
这个））！

是在使用词库的语法功能！词库语法是指"写在回复中间的一些特殊的文字"，词库语法在机器人回复的时候会发挥它的功能（比如上面的介个增加物品数量的语法），在成功执行后！词库语法会将“自己“替换为”执行的结果“。

根据你的需求的话！也许可以这样做到！
1. 设置一个触发词是“饭”它的回答中包含着不同的饭
2. 再设置一个“水”的触发词，它的回复内包含着不同的饮料！
3. 再设置一个触发词！“今天吃什么”，它的回复是：“你就吃(调:饭)，喝(调:水)吧！”

```
(调:a)
调用触发词"a"
```
这个语法被执行的时候，词库会从“a”这个触发词中抽取一条随机的回复。抽取后将抽到的回复作为结果！而我们知道语法执行完后会将”结果“替换掉它”自己“

基于这个语法的作用！我们可以使用它来触发“饭”这个问答，它会从你编写的”饭“的触发词中随机挑选一个回复作为结果，然后将你设定中的"(调:饭)"替换成"结果"

**Comment by BSTluo** [comment]
可能我讲的不太好！如果有不懂的话欢迎继续提问！

**Comment by BSTluo** [comment]
然后！编辑的权限的话！我下个版本会尝试加入那样的开关！
不过个人推荐最好不要开哦！
（曾经被熊孩子一晚上创建了百八十个库...）
（更加推荐手动为自己的朋友们设置他们能够编辑的库！）

另外！word.setedit可以切换编辑的存储库！
每次你编写问答的时候都是在向一个单独的存储库内添加。而setedit可以设置接下来你添加或删除的词库是向哪个词库添加！建议可以请朋友们每个人设置一个自己的存储库！这样的话大家编辑的内容不会互相冲突！而且导出导入的时候是以库作为单位来导入导出的！而word.addp设置编辑权限的时候可以设置每个人能编辑哪些存储库！

**Comment by DeepseaXX** [comment]
天哪，摸鱼干了会别的（也看了一会文档）就得到了如此详细贴心的回复，感谢。
关键词的(调:)就是我想实现的功能！防止这个“调”内部的词库被误触发，就行了！
还有一个没有理解的地方，关于词库和触发词的关系？
跨词库的同一个关键词，会怎么处理？
例如在default和Ku两个词库中，对Test有不同的回答的情况，我输入“Test”（或者`(调:Test)`），会以什么逻辑/流程进行判断呢？

**Comment by DeepseaXX** [comment]
关于编辑权限的问题，我自己想象的是两种方案。
一种是
针对某一个词库，例如“CiKu”，单独设置是否可以由所有人编辑，比如，可以继承Koishi的用户权限机制？例如
`word.setsavelevel [词库名] 3`，就是此词库支持koishi的用户等级3级以上的用户进行编辑？

另一种比较简单粗暴，就是直接设置全局的编辑权限，所有词库支持koishi的用户等级3级以上的用户进行编辑。

（其实我还是没有完全理解词库，存储格之间的关系…………让我再想想………………）

**Comment by BSTluo** [comment]
唔...调在发现调用自己的触发词的时候会弹出报错！应该还好...(除非刻意想做循环结构？)

然后词库的存储的话，可以把词库的整个存储系统类比成图书馆，词库的库，就像图书馆下的一个个书架。书架上面原本是空的，而触发词就是一本本书，而回复是触发词的一页，一个触发词拥有多个回答就像一本书有很多页。

每次开启word-core的时候，它会自动将整个图书馆内的书架和书架上的藏书统计一次，而每次有人说话的时候，就像从”图书馆查阅系统“中找一本书一样，找到那本书（触发词），然后抽取其中一页（回答）。而当找到有多个是多个书架都有同一本书的时候（多个库有同一个触发词的时候），系统会随机挑选结果中的一本书，而后抽取其中的一页（回答）


所以从结果上看的话，当多个词库存储库拥有相同的触发词的时候，其最终的结果就是从这些触发词的所有结果中随机抽取一个

**Comment by BSTluo** [comment]
唔...我为了方便...其实就木有接入koishi的用户权限（因为感觉内个绑定权限有点复杂....阿巴巴...要先给自己权限森魔的））

**Comment by DeepseaXX** [comment]
懂了，也就是说理论上每个人都可以拥有自己的词库，然后拥有一个叫饭的列表，
当有人调用“今天吃什么”的时候，会从所有人的饭列表里随机抽，
只不过概率上不是很公平（？
比如A词库里存在五种饭，B词库有一种饭
选择A或者B的时候概率0.5，
而A的内部每一种都只有0.1的全局概率，B的这唯一一种就是0.5
词库更多的话A的概率就更微妙了……

**Comment by BSTluo** [comment]
是这样的））））唔

**Comment by DeepseaXX** [comment]
> 唔...我为了方便...其实就木有接入koishi的用户权限（因为感觉内个绑定权限有点复杂....阿巴巴...要先给自己权限森魔的））

其实还挺一劳永逸的，（而且私心是想直接给default词库一个用户级的权限）

**Comment by BSTluo** [comment]
唔姆...确实..思考考...

**Comment by DeepseaXX** [comment]
> 
> 其实还挺一劳永逸的，（而且私心是想直接给default词库一个用户级的权限）

啊 没开小键盘
更正：0级权限*

**Comment by BSTluo** [comment]
唔不过作者权限最终可能都不会开放，因为我想...后面如果从词库市场下载词库的话...至少要防住有人改了别人的词库，就换壳了一下然后就再上传森魔的））

**Comment by BSTluo** [comment]
（然后唔权限的话理论上..给所有人一个word.edit.\*就可以允许大家都编辑所有的库...唔defalut的话需要default的作者添加其他人才可以...不过我感觉也许可以尝试一下当作者添加名为\"\*\"的作者的时候允许所有人成为作者(?)

**Comment by DeepseaXX** [comment]
修改公开词库确实是，一个问题……
我突然想到………作为暂时对策的话，我自己魔改一下验证权限的部分，好像也不是不行…………

顺便刚才发现在group里进行word.add之类的操作都不会返回提示语，这是feature吗（

**Comment by BSTluo** [comment]
唔..然后我上述说的词库是指词库存储库，而存储格的概念可能和你想象中的不太一样，文档中的存储格和存储库大概是两个东东
word.setedit 设置所编辑的库
word.setsave 设置存储格

对于存储库，看到上面也许应该了解了！（如果不太懂的话欢迎继续提问哦！

而存储格的话！通过看小鱼干的内个示例，你会发现(+:物品名称:数量)这个语法会为触发者添加物品，而物品的数据，其实存储在玩家数据库。还是以图书馆为例的话。玩家数据库是图书馆，每个玩家都有自己的书架，而存储格子则代表了每一本书，而物品的数据就写在了这本书里，书的内容大概是：
```
鱼干:10
金币:10
德玛西亚:1
哼哼啊:114514
```
物品名称:数量


每个词库存储库都可以为自己设置存储格，每次回复被触发的时候，如果回复中有(+:物品名称:数量)这样会对玩家数据进行变化的语法的时候，词库会前往对应的存储格进行数据的增加或减少。每个存储库的默认的存储格子都是default，这意味着所有的词库其实是共用一片存储数据区域的。这样会产生一定的问题：比如a词库1金币可以购买10条鱼，而b词库处1金币可以购买100条，这样会导致汇率爆炸）此时可以通过为两个词库存储库设定不同的存储格子，而使得两个词库最终写入数据到不同的区域，从而避免汇率爆炸

**Comment by BSTluo** [comment]
（阿巴阿巴，group是森魔（？）

**Comment by BSTluo** [comment]
唔如果需要去魔改的话
word.add指令处的以下两行可以删除，这个是判断是否拥有编辑权限的
```
const hasPermission = await ctx.word.permission.isHave(uid, `word.edit.${nowWordDB}`);

if (!hasPermission && !config.masterID.includes(uid)) { return `<at name="${session.username}" /> 你没有词库【${nowWordDB}】的编辑权限`; }
```

然后再将此处的uid设置为自己的id（我的例子写的是自己的qq号，请不要模仿哦），id可以通过word.id查看
```
const a = await ctx.word.editor.addWordItem(nowWordDB, uid, question, answer);
修改为：
const a = await ctx.word.editor.addWordItem(nowWordDB, "1946831552", question, answer);
```
此处的id是词库用于判断是谁在添加词库的。

**Comment by BSTluo** [comment]
（这样的话词库会判断始终是你在添加词库

**Comment by BSTluo** [comment]
word.rm指令处也是类似变化，删除两行和修改内一行的uid为自己就好啦

**Comment by BSTluo** [comment]
（话说，还有个方法就是把word.rm指令和word.add指令下的
```
const uid = session.userId;
改成
const uid = "1946831552";
```

直接修改词库插件获取到的用户id为你自己的）这样的话词库也可以判断始终是你一个人在修改词库）某种意义上的也是公开x

**Comment by DeepseaXX** [comment]
> （话说，还有个方法就是把word.rm指令和word.add指令下的
> 
> ```
> const uid = session.userId;
> 改成
> const uid = "1946831552";
> ```
> 
> 直接修改词库插件获取到的用户id为你自己的）这样的话词库也可以判断始终是你一个人在修改词库）某种意义上的也是公开x

好好好，这个方法比较好，也不会改动原本的逻辑，我去试试（刚回家）

**Comment by BSTluo** [comment]
> 好好好，这个方法比较好，也不会改动原本的逻辑，我去试试（刚回家）

好！！
![3000-CE](https://github.com/user-attachments/assets/e46adcc5-7108-4ca3-a3e8-ef310eadcb9b)

**Comment by DeepseaXX** [comment]
> const uid = session.userId;

群……群聊……
私聊中所有消息都可以正常触发，
群聊中触发关键词后的回复是正常的，但诸如word.add之类的，返回文本是发不出来的

日志如下
```
2024-09-20 21:02:35 [W] session Error: Error with request send_group_msg, args: {"group_id":775756367,"message":[{"type":"at","data":{"name":"Ana Amari"}},{"type":"text","data":{"text":" 添加到【default】词库成功，序号为【1】"}}]}, retcode: 1200
                            at _Internal._get (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
                            at async OneBotMessageEncoder.flush (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:761:330)
                            at async OneBotMessageEncoder.send (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:620:5)
                            at async Proxy.sendMessage (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:355:22)
                            at async C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2061:7
                            at async Proxy.withScope (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1968:22)
                            at async next (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\XxDee\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
```

**Comment by BSTluo** [comment]
唔其他插件能够使用木？

**Comment by BSTluo** [comment]
（话说要不新开个issues）））方便之后有人查看这个问题）））

**Comment by DeepseaXX** [comment]
好的

**Comment by BSTluo** [comment]
@DeepseaXX 另外还有一些小知识点，词库的语法是支持嵌套的：
比如有个获取当前是本月第几号的语法：`(time:4)`

它的返回值是一个数字，这就意味着它能够使用在任何需要数字的地方：
比如：`(+:鱼:(time:4))`

词库在解析每个语法的时候，检测到参数的值是一个`语法`或者`包含语法`的时候，会将参数内的语法执行后，将返回值返回！

举个例子，有个回复是这样的：你获得了(+:鱼:(time:4))条鱼，词库进行解析的时候是这样的：
```
你获得了(+:鱼:(time:4))
↓
检测到词库语法(+:鱼:(time:4))
↓
开始抽取物品名称：鱼
开始抽取物品数量：(time:4)
↓
发现物品数量为词库语法
↓
开始执行词库语法：(time:4)
↓
当前是26号，(time:4)执行结果是26
↓
释放结果：26
↓
(+:鱼:26)
执行语句
↓
各参数无词库语法，执行
↓
添加26条鱼，释放结果
↓
你获得了26条鱼
```

**Comment by BSTluo** [comment]
这就意味着你甚至可以如下方式拼接判断物品数量的语法和随机数的语法：
(?:鱼:>:(~:1:100))
