### ISSUE TITLE
使用word find搜索某关键词之后，回复中出现了三个default……如何手动删除多余的词库？

### ISSUE THREAD

**Issue by DeepseaXX** [BSTluo/koishi-plugin-word-core#13]
你好！由于今天是工作日，所以我又来（摸鱼）了！

可能也跟此链接有间接关联？
[无指令查看所有词库 #6](https://github.com/BSTluo/koishi-plugin-word-core/issues/6)

先说症状
对话如下

> 我：word find 食物列表
> Bot：此关键词存在以下词库：
> 1. default
> 2. default
> 3. default

（没错，三个default）
我大概知道原因，因为我昨天闲的蛋疼，手动直接魔改了数据库的存储，然后又反复试错反复保存……
现在我想知道如何手动（而不是通过与bot的对话）删除多余的这几个default？

以及，如何批量添加触发词的回答，而不是通过对话形式逐个`word add`，或者对话形式一次添加多个回答？
（是词库Blocky吗？）
（因为我在利用word core手搓remake和吃什么/喝什么，所以需要某触发词里包含大量的词汇……）

**Comment by BSTluo** [comment]
唔，感觉目前要批量添加的话还需要是手动进数据库改，词库的存储的数据的格式是这样的：
![image](https://github.com/user-attachments/assets/1f8774fb-b9c5-4546-a074-0792a85f14fb)

（记得因为历史遗留问题的原因，所以，这里的id要和词库的name一致
![image](https://github.com/user-attachments/assets/e95403c8-65e8-4de9-8962-40df96fc4f5f)

**Comment by BSTluo** [comment]
（说起来我好像记得我获取所有词库的列表那个，好像输出的文案错了

**Comment by DeepseaXX** [comment]
同时存在3个default的症状在我重装插件之后消失了！
我也不知道中间发生了什么……
总之现在是正常了……

批量添加词条，我目前也是用的直接手搓数据库的方法。

但是这样很容易改出问题，例如
疑似在当前词库不存在A问题时，直接修改输入库加入A问题的词条会有点很抽象的问题…………可能跟Cache有关？
所谓的3个default也是在一顿骚操作之后出现的，反正现在重装之后是没问题了……

所以现在保险起见，我都是先通过文本指令执行一次 word add A B，在数据库里出现A词条之后再添加更多的词条

**Comment by BSTluo** [comment]
确实如此，和cache应该有一定的关系，根据帖子
https://github.com/BSTluo/koishi-plugin-word-core/issues/10#issuecomment-2363065204中的

> 每次开启word-core的时候，它会自动将整个图书馆内的书架和书架上的藏书统计一次

其实一般word.add录入词库的时候就是正常的登记入库的流程，而修改词库之后，就像图书馆中出现了超自然力量新增了一些图书，而图书管理系统因为木有统计，所以不知道））


在直接对数据库进行修改后！记得！要重载一次word-core插件哦！
